# This is a basic workflow to help you get started with Actions



# Controls when the workflow will run

  # Triggers the workflow on push or pull request events but only for the "main" branch





  # Allows you to run this workflow manually from the Actions tab


# A workflow run is made up of one or more jobs that can run sequentially or in parallel

  # This workflow contains a single job called "build"

    # The type of runner that the job will run on


    # Steps represent a sequence of tasks that will be executed as part of the job

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it


      # Runs a single command using the runners shell

        

      # Runs a set of commands using the runners shell




& "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AfgeXvt6WuTJpDgVl_wVLII32UTkZqvAB0xftuf5MrDXVMtDJgKfFZ9GTaH9M6Udt_-hFw" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME
